/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, MeshRefractionMaterial, MeshTransmissionMaterial } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/models/logo-model.glb");

	const ref = useRef();
	// Hold state for hovered and clicked events
	const [hovered, hover] = useState(false);
	const [clicked, click] = useState(false);

	// Subscribe this component to the render-loop, rotate the mesh every frame
	useFrame((state, delta) => !hovered && (ref.current.rotation.y += delta / 1.2));

	// const materialProps = {
	// 	thickness: 1.6,
	// 	roughness: 0,
	// 	clearcoat: 0,
	// 	clearcoatRoughness: 1,
	// 	transmission: 0.98,
	// 	ior: 13,
	// 	envMapIntensity: 1,
	// 	color: "#ffffff",
	// 	attenuationTint: "#c10000",
	// 	attenuationDistance: 1,
	// };

	const materialProps = {
		thickness: 0,
		roughness: 0,
		clearcoat: 1,
		clearcoatRoughness: 1,
		transmission: 0,
		ior: 16,
		envMapIntensity: 0,
		color: "#ffffff",
		attenuationTint: "#ebebeb",
		attenuationDistance: 0,
	};

	return (
		<group
			{...props}
			dispose={null}>
			<group
				userData={{
					"assets used": {
						"f9f9ff9d-c703-4fbc-92b8-3e5d452848ca": {
							thumbnail:
								"thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 100,
							texture_size_meters: 1,
							pk: 68399,
							url: "https://www.blenderkit.com/api/v1/assets/419170c4-6fff-4dc4-86fc-dea9554ebf81/",
							id: "419170c4-6fff-4dc4-86fc-dea9554ebf81",
							assetBaseId: "f9f9ff9d-c703-4fbc-92b8-3e5d452848ca",
							versionNumber: 1,
							author: {
								id: "245077",
								firstName: "Rous",
								lastName: "Kristall",
								gravatarHash: "1f11fedec5ee30a50a8870eecc8a3796",
								avatar128: "/avatar-redirect/fff36896-b294-4862-81bf-bc90768e876f/128/",
								avatar256: "/avatar-redirect/fff36896-b294-4862-81bf-bc90768e876f/256/",
								avatar512: "/avatar-redirect/fff36896-b294-4862-81bf-bc90768e876f/512/",
								aboutMe: "",
								aboutMeUrl: "https://www.artstation.com/rous_kristall",
								fullName: "Rous Kristall",
								socialNetworks: [
									{
										socialNetwork: {
											name: "ArtStation",
											icon: '<i class="fab fa-artstation" title="ArtStation"></i><span class="sr-only">ArtStation</span>',
											order: 5,
										},
										url: "https://www.artstation.com/rous_kristall",
									},
									{
										socialNetwork: {
											name: "YouTube",
											icon: '<i class="fab fa-youtube" title="YouTube"></i><span class="sr-only">YouTube</span>',
											order: 1,
										},
										url: "https://www.youtube.com/@Subdivisors",
									},
								],
								app_id: 2551,
								tooltip: "Rous Kristall\n\n",
								gravatarImg:
									"/var/folders/fv/11yf7k15197bqmn2mqbq1h_80000gn/T/bktemp_naman/bkit_g/245077.jpg",
							},
							name: "Glass",
							displayName: "Glass",
							description:
								"Decorative glass shader with realistic dispercion and wavy displacement pattern, perfect solution for your motion design cases. You can change color, transparency, displacement scale and distorion or even unable it in only one node. \r\n\r\nFeel free to use it in your work or personal projects :)",
							descriptionHtml:
								"<p>Decorative glass shader with realistic dispercion and wavy displacement pattern, perfect solution for your motion design cases. You can change color, transparency, displacement scale and distorion or even unable it in only one node. </p>\n<p>Feel free to use it in your work or personal projects :)</p>",
							assetType: "material",
							category: "glass",
							adult: false,
							isFree: true,
							tags: [
								"glass",
								"decor",
								"decorative",
								"motion",
								"design",
								"dispercion",
								"wave",
								"displacement",
								"height",
								"transparent",
								"glossy",
								"shader",
								"rough",
								"clean color vright",
							],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "3.6.5",
							addonVersion: "3.8.0",
							created: "2023-10-25T01:11:04.891117+02:00",
							lastUserInteraction: "2023-10-25T01:11:15.876069+02:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/258938/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2023-10-25T01:11:16.208599+02:00",
									modified: "2023-10-25T01:11:16.208654+02:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/419170c46fff4dc486fcdea9554ebf81/files/blend_109eaae8-89fd-4c57-9824-06f44e850502.blend",
									file_name: "blend_109eaae8-89fd-4c57-9824-06f44e850502.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/258937/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.1024x1024_q85_crop-%2C.png",
									created: "2023-10-25T01:11:15.904368+02:00",
									modified: "2023-10-25T01:11:15.904407+02:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 4632,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.256x256_q85_crop-%2C.png.webp?webp_generated=1698309393",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.512x512_q85_crop-%2C.png.webp?webp_generated=1698309393",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1698309393",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1698309393",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.256x256_q85.png.webp?webp_generated=1698309393",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.512x512_q85.png.webp?webp_generated=1698309393",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.1024x1024_q85.png.webp?webp_generated=1698309393",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/419170c46fff4dc486fcdea9554ebf81/files/thumbnail_a9bbd523-72ce-43cd-b673-f6485fd002a5.png.2048x2048_q85.png.webp?webp_generated=1698309393",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1698309393,
							score: 405,
							ratingsMedian: { bookmarks: 1, workingHours: 4.5, quality: 10, virtualPrice: null },
							ratingsAverage: { bookmarks: 1, workingHours: 4.5, quality: 9, virtualPrice: null },
							ratingsCount: { bookmarks: 307, workingHours: 4, quality: 6, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 307,
								workingHours: 14.200000002980232,
								quality: 54,
								virtualPrice: null,
								score: 405,
							},
							lastBlendUpload: "2023-10-24T23:11:16.208599+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2023-10-24T23:11:15.904368+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								procedural: true,
								materialStyle: "realistic",
								condition: "new",
								engine: "cycles",
								shaders: ["mix shader", "refraction", "glass"],
								uv: false,
								nodeCount: 15,
								textureCount: 0,
								megapixels: 0,
								imageAltTextGen4v:
									"Realistic Blender 3D glass material with customizable color, transparency, and distortion for creative motion design.",
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: { aname: "Glass", author_text: "by Rous Kristall", quality: "9" },
							resolution: "resolution_2K",
						},
						"df615fc5-6f62-4233-8734-83751a02de44": {
							thumbnail:
								"thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 100,
							texture_size_meters: 1,
							pk: 80730,
							url: "https://www.blenderkit.com/api/v1/assets/a444bea2-a767-4055-bb1e-e49bd96e9301/",
							id: "a444bea2-a767-4055-bb1e-e49bd96e9301",
							assetBaseId: "df615fc5-6f62-4233-8734-83751a02de44",
							versionNumber: 1,
							author: {
								id: "156012",
								firstName: "Mikhail",
								lastName: "Zabolotny",
								gravatarHash: "b921533d6bf4fa302e4c051098632416",
								avatar128: "/avatar-redirect/d7cde77d-d85b-4557-9cb5-29411aa1d4b7/128/",
								avatar256: "/avatar-redirect/d7cde77d-d85b-4557-9cb5-29411aa1d4b7/256/",
								avatar512: "/avatar-redirect/d7cde77d-d85b-4557-9cb5-29411aa1d4b7/512/",
								aboutMe: "",
								aboutMeUrl: "https://www.artstation.com/michail_zabolotny",
								fullName: "Mikhail Zabolotny",
								socialNetworks: [],
							},
							name: "Glass",
							displayName: "Glass",
							description: "Excellent glass with scratches",
							descriptionHtml: "<p>Excellent glass with scratches</p>",
							assetType: "material",
							category: "glass",
							adult: false,
							isFree: true,
							tags: [
								"glass",
								"stained",
								"scratches",
								"transparent",
								"opacity",
								"glossy",
								"mirror",
								"cracked",
							],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "4.0.2",
							addonVersion: "3.11.0",
							created: "2024-02-17T01:31:36.305199+01:00",
							lastUserInteraction: "2024-02-17T01:31:46.285876+01:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/328285/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2024-02-17T01:31:45.730439+01:00",
									modified: "2024-02-17T01:31:45.730457+01:00",
									mimeType: null,
									resolution: null,
								},
								{
									fileType: "resolution_0_5K",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/328308/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2024-02-17T07:25:56.754363+01:00",
									modified: "2024-02-17T07:25:56.754383+01:00",
									mimeType: null,
									resolution: null,
								},
								{
									fileType: "resolution_1K",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/328307/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2024-02-17T07:25:56.204119+01:00",
									modified: "2024-02-17T07:25:56.204174+01:00",
									mimeType: null,
									resolution: null,
								},
								{
									fileType: "resolution_2K",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/328306/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2024-02-17T07:25:55.531547+01:00",
									modified: "2024-02-17T07:25:55.531564+01:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/a444bea2a7674055bb1ee49bd96e9301/files/resolution_2K_7aa16911-6adf-44f7-b820-c062ec65f6d9.blend",
									file_name: "resolution_2K_7aa16911-6adf-44f7-b820-c062ec65f6d9.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/328284/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.1024x1024_q85_crop-%2C.png",
									created: "2024-02-17T01:31:44.114647+01:00",
									modified: "2024-02-17T01:31:44.114664+01:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 8232,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.256x256_q85_crop-%2C.png.webp?webp_generated=1708151166",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.512x512_q85_crop-%2C.png.webp?webp_generated=1708151166",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1708151166",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1708151166",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.256x256_q85.png.webp?webp_generated=1708151166",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.512x512_q85.png.webp?webp_generated=1708151166",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.1024x1024_q85.png.webp?webp_generated=1708151166",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a444bea2a7674055bb1ee49bd96e9301/files/thumbnail_a30e7c3e-5774-4a2b-8c90-b3028f37d6e3.png.2048x2048_q85.png.webp?webp_generated=1708151166",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1708151166,
							score: 475,
							ratingsMedian: { bookmarks: 1, workingHours: 5, quality: 10, virtualPrice: null },
							ratingsAverage: { bookmarks: 1, workingHours: 5, quality: 9.5, virtualPrice: null },
							ratingsCount: { bookmarks: 174, workingHours: 4, quality: 4, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 174,
								workingHours: 15.5,
								quality: 38,
								virtualPrice: null,
								score: 475,
							},
							lastBlendUpload: "2024-02-17T00:31:45.730439+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2024-02-17T00:31:44.114647+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: "2024-02-17T06:25:56.754363+00:00",
							dictParameters: {
								textureResolutionMax: 2048,
								textureSizeMeters: 1,
								procedural: false,
								materialStyle: "realistic",
								purePbr: true,
								engine: "cycles",
								shaders: ["principled"],
								animated: false,
								pbrType: "metallic",
								uv: true,
								textureResolutionMin: 2048,
								nodeCount: 12,
								textureCount: 2,
								megapixels: 8,
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [512, 1024, 2048],
							max_resolution: 2048,
							tooltip_data: { aname: "Glass", author_text: "by Mikhail Zabolotny", quality: "10" },
							resolution: "resolution_2K",
						},
						"0864b70c-9e25-4844-9486-66a0f24b6596": {
							thumbnail:
								"thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 0,
							texture_size_meters: 1,
							pk: 9175,
							url: "https://www.blenderkit.com/api/v1/assets/ceea1ad4-9c3b-44a3-a4d1-8be89ff5660a/",
							id: "ceea1ad4-9c3b-44a3-a4d1-8be89ff5660a",
							assetBaseId: "0864b70c-9e25-4844-9486-66a0f24b6596",
							versionNumber: 1,
							author: {
								id: "42913",
								firstName: "Nobody",
								lastName: "",
								gravatarHash: "823d05a61b2fa0dd7c17a66de7198da5",
								avatar128: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/128/",
								avatar256: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/256/",
								avatar512: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/512/",
								aboutMe:
									"Mostly i do interior stuff\r\n\r\nYou can contact me here: lukaspistek666@gmail.com",
								aboutMeUrl: "https://www.deviantart.com/relev4nt",
								fullName: "Nobody ",
								socialNetworks: [],
								app_id: 2551,
								tooltip:
									"Nobody \n\nMostly i do interior stuff\n\nYou can contact me here: lukaspistek666@gmail.com\n",
								gravatarImg:
									"/var/folders/fv/11yf7k15197bqmn2mqbq1h_80000gn/T/bktemp_naman/bkit_g/42913.jpg",
							},
							name: "Drinking Glass Texture",
							displayName: "Drinking Glass Texture",
							description: "Needs unwrap, You can change the colors",
							descriptionHtml: "<p>Needs unwrap, You can change the colors</p>",
							assetType: "material",
							category: "glass",
							adult: false,
							isFree: true,
							tags: ["drinking", "glass"],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "2.91.0",
							addonVersion: "1.0.32",
							created: "2020-10-09T23:49:20.555396+02:00",
							lastUserInteraction: "2020-10-19T20:22:34.960261+02:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/25123/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2020-10-09T23:49:34.106543+02:00",
									modified: "2020-12-11T17:52:14.780865+01:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/blend_ba87a548-0d82-4fb2-9f7f-20e508007c85.blend",
									file_name: "blend_ba87a548-0d82-4fb2-9f7f-20e508007c85.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/25122/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.1024x1024_q85_crop-%2C.png",
									created: "2020-10-09T23:49:31.597173+02:00",
									modified: "2020-12-11T17:52:14.798372+01:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 847,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.256x256_q85_crop-%2C.png.webp?webp_generated=1608308047",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.512x512_q85_crop-%2C.png.webp?webp_generated=1608308047",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1608308047",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1608308047",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.256x256_q85.png.webp?webp_generated=1608308047",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.512x512_q85.png.webp?webp_generated=1608308047",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.1024x1024_q85.png.webp?webp_generated=1608308047",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/ceea1ad49c3b44a3a4d18be89ff5660a/files/thumbnail_6e371fce-a0a3-4c6a-942e-da093d8da1d4.png.2048x2048_q85.png.webp?webp_generated=1608308047",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1608308047,
							score: 243.75,
							ratingsMedian: { bookmarks: 1, workingHours: 3, quality: 10, virtualPrice: null },
							ratingsAverage: { bookmarks: 1, workingHours: 3, quality: 8.125, virtualPrice: null },
							ratingsCount: { bookmarks: 110, workingHours: 7, quality: 8, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 110,
								workingHours: 17.5,
								quality: 65,
								virtualPrice: null,
								score: 243.75,
							},
							lastBlendUpload: "2020-10-09T21:49:34.106543+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2020-10-09T21:49:31.597173+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								procedural: true,
								materialStyle: "realistic",
								purePbr: false,
								engine: "cycles",
								shaders: ["glass", "reroute"],
								animated: false,
								uv: true,
								nodeCount: 37,
								textureCount: 0,
								megapixels: 0,
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: {
								aname: "Drinking Glass Texture",
								author_text: "by Nobody ",
								quality: "8",
							},
							resolution: "blend",
						},
						"ab66d11e-f868-4575-a564-119a2d5a9f17": {
							thumbnail:
								"thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 0,
							texture_size_meters: 1,
							pk: 8929,
							url: "https://www.blenderkit.com/api/v1/assets/c031d9e5-0b15-45b7-9afe-97e53e45739f/",
							id: "c031d9e5-0b15-45b7-9afe-97e53e45739f",
							assetBaseId: "ab66d11e-f868-4575-a564-119a2d5a9f17",
							versionNumber: 1,
							author: {
								id: "953",
								firstName: "BumpkinCZ",
								lastName: "",
								gravatarHash: "e979639ca601eb721e7a8d4055ae2f04",
								avatar128: "/avatar-redirect/cf446502-bef4-4195-a028-fc9459be3743/128/",
								avatar256: "/avatar-redirect/cf446502-bef4-4195-a028-fc9459be3743/256/",
								avatar512: "/avatar-redirect/cf446502-bef4-4195-a028-fc9459be3743/512/",
								aboutMe:
									"Links to my work and sites:\r\nhttps://www.instagram.com/bumpkincze/\r\nhttps://www.facebook.com/BumpkinCZE/\r\nhttps://www.artstation.com/bumpkin",
								aboutMeUrl: "https://www.artstation.com/bumpkin",
								fullName: "BumpkinCZ ",
								socialNetworks: [],
							},
							name: "Carlight shingle chrome white",
							displayName: "Carlight shingle chrome white",
							description: "Carlight_shingle_chrome_white",
							descriptionHtml: "<p>Carlight_shingle_chrome_white</p>",
							assetType: "material",
							category: "metal",
							adult: false,
							isFree: true,
							tags: ["Car", "light", "triangle", "chrome", "white", "truck", "vehicle"],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "2.81.16",
							addonVersion: "1.0.28",
							created: "2020-09-30T14:58:41.294960+02:00",
							lastUserInteraction: "2020-09-30T17:21:03.191932+02:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/24553/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2020-09-30T15:00:10.097416+02:00",
									modified: "2020-12-11T09:31:51.972595+01:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/c031d9e50b1545b79afe97e53e45739f/files/blend_a315e921-3e6a-45ed-be1b-c11f47aedb74.blend",
									file_name: "blend_a315e921-3e6a-45ed-be1b-c11f47aedb74.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/24552/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.1024x1024_q85_crop-%2C.png",
									created: "2020-09-30T14:58:57.606204+02:00",
									modified: "2020-12-11T09:31:51.988477+01:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 39775,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.256x256_q85_crop-%2C.png.webp?webp_generated=1608306362",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.512x512_q85_crop-%2C.png.webp?webp_generated=1608306362",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1608306362",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1608306362",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.256x256_q85.png.webp?webp_generated=1608306362",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.512x512_q85.png.webp?webp_generated=1608306362",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.1024x1024_q85.png.webp?webp_generated=1608306362",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/c031d9e50b1545b79afe97e53e45739f/files/thumbnail_747fc9b8-4dea-43e3-9802-1d4f1434d4ab.png.2048x2048_q85.png.webp?webp_generated=1608306362",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1608306362,
							score: 384,
							ratingsMedian: { bookmarks: 1, workingHours: 4, quality: 10, virtualPrice: null },
							ratingsAverage: { bookmarks: 1, workingHours: 4, quality: 9.6, virtualPrice: null },
							ratingsCount: { bookmarks: 40, workingHours: 3, quality: 5, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 40,
								workingHours: 13,
								quality: 48,
								virtualPrice: null,
								score: 384,
							},
							lastBlendUpload: "2020-09-30T13:00:10.097416+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2020-09-30T12:58:57.606204+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								materialStyle: "realistic",
								purePbr: true,
								engine: "cycles",
								shaders: [""],
								animated: false,
								pbrType: "metallic",
								uv: false,
								imageAltTextGen4v:
									"High-resolution PBR chrome white metal texture for 3D rendering and Blender artists.",
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: {
								aname: "Carlight shingle chrome white",
								author_text: "by BumpkinCZ ",
								quality: "10",
							},
							resolution: "blend",
						},
						"f0ffb99d-4717-42be-aa29-d43d3839db9c": {
							thumbnail:
								"thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 0,
							texture_size_meters: 1,
							pk: 20659,
							url: "https://www.blenderkit.com/api/v1/assets/16022e10-a1b8-4329-80b7-30a67c04cbe7/",
							id: "16022e10-a1b8-4329-80b7-30a67c04cbe7",
							assetBaseId: "f0ffb99d-4717-42be-aa29-d43d3839db9c",
							versionNumber: 1,
							author: {
								id: "42913",
								firstName: "Nobody",
								lastName: "",
								gravatarHash: "823d05a61b2fa0dd7c17a66de7198da5",
								avatar128: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/128/",
								avatar256: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/256/",
								avatar512: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/512/",
								aboutMe:
									"Mostly i do interior stuff\r\n\r\nYou can contact me here: lukaspistek666@gmail.com",
								aboutMeUrl: "https://www.deviantart.com/relev4nt",
								fullName: "Nobody ",
								socialNetworks: [],
							},
							name: "Neochrome Metal v2",
							displayName: "Neochrome Metal v2",
							description: "I have made second version of this material",
							descriptionHtml: "<p>I have made second version of this material</p>",
							assetType: "material",
							category: "metal",
							adult: false,
							isFree: true,
							tags: ["neochrome", "metal", "iron", "steel", "blue", "chrome"],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "2.93.1",
							addonVersion: "2.93.0",
							created: "2021-08-02T13:48:57.990349+02:00",
							lastUserInteraction: "2021-08-02T13:50:14.113648+02:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/75030/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2021-08-02T13:50:11.478319+02:00",
									modified: "2021-08-02T13:50:14.347800+02:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/16022e10a1b8432980b730a67c04cbe7/files/blend_529cc7b9-9ea0-4f3d-9f1f-14804eb4f36c.blend",
									file_name: "blend_529cc7b9-9ea0-4f3d-9f1f-14804eb4f36c.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/75028/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.1024x1024_q85_crop-%2C.png",
									created: "2021-08-02T13:49:05.742749+02:00",
									modified: "2021-08-02T13:49:16.453950+02:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 685,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.256x256_q85_crop-%2C.png.webp?webp_generated=1628852481",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.512x512_q85_crop-%2C.png.webp?webp_generated=1628852481",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1628852481",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1628852481",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.256x256_q85.png.webp?webp_generated=1628852481",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.512x512_q85.png.webp?webp_generated=1628852481",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.1024x1024_q85.png.webp?webp_generated=1628852481",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/16022e10a1b8432980b730a67c04cbe7/files/thumbnail_da91ff00-ca9e-4221-bbfd-b32b6360e365.png.2048x2048_q85.png.webp?webp_generated=1628852481",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1628852481,
							score: 391.66666666666663,
							ratingsMedian: { bookmarks: 1, workingHours: 5, quality: 8.5, virtualPrice: null },
							ratingsAverage: {
								bookmarks: 0.9871794871794872,
								workingHours: 5,
								quality: 7.833333333333333,
								virtualPrice: null,
							},
							ratingsCount: { bookmarks: 78, workingHours: 5, quality: 6, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 77,
								workingHours: 20,
								quality: 47,
								virtualPrice: null,
								score: 391.66666666666663,
							},
							lastBlendUpload: "2021-08-02T11:50:11.478319+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2021-08-02T11:49:05.742749+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								procedural: true,
								materialStyle: "realistic",
								purePbr: false,
								engine: "cycles",
								shaders: ["mix shader", "glossy", "diffuse"],
								animated: false,
								uv: false,
								nodeCount: 16,
								textureCount: 0,
								megapixels: 0,
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: {
								aname: "Neochrome Metal v2",
								author_text: "by Nobody ",
								quality: "8",
							},
							resolution: "blend",
						},
						"c26486fe-a2bc-4e64-a712-75477e346cf1": {
							thumbnail:
								"thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 0,
							texture_size_meters: 1,
							pk: 34880,
							url: "https://www.blenderkit.com/api/v1/assets/81802cea-f5c5-4ae0-81f3-b6efb8bb2993/",
							id: "81802cea-f5c5-4ae0-81f3-b6efb8bb2993",
							assetBaseId: "c26486fe-a2bc-4e64-a712-75477e346cf1",
							versionNumber: 1,
							author: {
								id: "42913",
								firstName: "Nobody",
								lastName: "",
								gravatarHash: "823d05a61b2fa0dd7c17a66de7198da5",
								avatar128: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/128/",
								avatar256: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/256/",
								avatar512: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/512/",
								aboutMe:
									"Mostly i do interior stuff\r\n\r\nYou can contact me here: lukaspistek666@gmail.com",
								aboutMeUrl: "https://www.deviantart.com/relev4nt",
								fullName: "Nobody ",
								socialNetworks: [],
							},
							name: "Top Coating Layer for CDs",
							displayName: "Top Coating Layer for CDs",
							description:
								"NOTE! You have to use UV Unwrap First! The main body of the CD is made of hard plastic known as polycarbonate with a reflective metallic layer. This layer is coated with metallic acrylic plastic. This metal is aluminum. In this layer, the data are stored using the laser light which reflects the coated layer for reading and writing the data.",
							descriptionHtml:
								"<p>NOTE! You have to use UV Unwrap First! The main body of the CD is made of hard plastic known as polycarbonate with a reflective metallic layer. This layer is coated with metallic acrylic plastic. This metal is aluminum. In this layer, the data are stored using the laser light which reflects the coated layer for reading and writing the data.</p>",
							assetType: "material",
							category: "metal",
							adult: false,
							isFree: true,
							tags: [
								"CD",
								"metallic",
								"polycarbonate",
								"neochrome",
								"metal",
								"iron",
								"steel",
								"blue",
								"chrome",
							],
							license: "royalty_free",
							sourceAppName: "blender",
							sourceAppVersion: "3.1.0",
							addonVersion: "3.1.0",
							created: "2022-07-09T11:06:31.561454+02:00",
							lastUserInteraction: "2022-07-09T11:06:44.938807+02:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/125077/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2022-07-09T11:06:43.726698+02:00",
									modified: "2022-07-09T11:06:44.392158+02:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/blend_97d79332-a4ad-4810-a77f-fa450a026a5b.blend",
									file_name: "blend_97d79332-a4ad-4810-a77f-fa450a026a5b.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/125076/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.1024x1024_q85_crop-%2C.png",
									created: "2022-07-09T11:06:36.657455+02:00",
									modified: "2022-07-09T11:06:42.000883+02:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 1697,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.256x256_q85_crop-%2C.png.webp?webp_generated=1657799150",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.512x512_q85_crop-%2C.png.webp?webp_generated=1657799150",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1657799150",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1657799150",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.256x256_q85.png.webp?webp_generated=1657799150",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.512x512_q85.png.webp?webp_generated=1657799150",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.1024x1024_q85.png.webp?webp_generated=1657799150",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/81802ceaf5c54ae081f3b6efb8bb2993/files/thumbnail_052dc4a3-5d48-41cb-9851-bd14fd2e57d4.png.2048x2048_q85.png.webp?webp_generated=1657799150",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1657799150,
							score: 360,
							ratingsMedian: { bookmarks: 1, workingHours: 4, quality: 9, virtualPrice: null },
							ratingsAverage: {
								bookmarks: 0.9811320754716981,
								workingHours: 4,
								quality: 9,
								virtualPrice: null,
							},
							ratingsCount: { bookmarks: 53, workingHours: 1, quality: 2, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 52,
								workingHours: 4,
								quality: 18,
								virtualPrice: null,
								score: 360,
							},
							lastBlendUpload: "2022-07-09T09:06:43.726698+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2022-07-09T09:06:36.657455+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								procedural: true,
								materialStyle: "realistic",
								condition: "new",
								purePbr: false,
								engine: "cycles",
								shaders: ["glossy", "mix shader", "anisotropic", "add shader", "glass", "diffuse"],
								animated: false,
								uv: false,
								nodeCount: 34,
								textureCount: 0,
								megapixels: 0,
								imageCaptionInterrogator:
									"there is a green ball with a white circle on it, iridescent specular highlights, substance render, floating translucent graphics, cel shaded:15, clear [[bronze]] face [mask], unreal engine 5 - w 1024, marble reflexes, oil slick colors, art render, c4, d render",
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: {
								aname: "Top Coating Layer for CDs",
								author_text: "by Nobody ",
								quality: "9",
							},
							resolution: "blend",
						},
						"dd250922-34f0-48cc-b631-e8c46397100f": {
							addonVersion: "1.0.32",
							adult: false,
							assetBaseId: "dd250922-34f0-48cc-b631-e8c46397100f",
							assetType: "material",
							author: {
								aboutMe:
									"Mostly i do interior stuff\r\n\r\nYou can contact me here: lukaspistek666@gmail.com",
								avatar128: "/avatar-redirect/b8598a7e-0182-40e5-8f82-b6cfa582af85/128/",
								firstName: "Nobody",
								fullName: "Nobody ",
								gravatarHash: "823d05a61b2fa0dd7c17a66de7198da5",
								gravatarImg:
									"/var/folders/fv/11yf7k15197bqmn2mqbq1h_80000gn/T/bktemp_naman/bkit_g/42913.jpg",
								id: "42913",
								lastName: "",
								socialNetworks: [],
								tooltip:
									"Nobody \n\nMostly i do interior stuff\n\nYou can contact me here: lukaspistek666@gmail.com\n",
							},
							available_resolutions: [],
							canDownload: true,
							canDownloadError: true,
							category: "metal",
							created: "2020-10-02T00:23:58.928036+02:00",
							description: "Chrome",
							dictParameters: {
								animated: false,
								engine: "cycles",
								materialStyle: "realistic",
								megapixels: 0,
								nodeCount: 11,
								procedural: true,
								purePbr: false,
								shaders: ["add shader", "glossy", "principled"],
								textureCount: 0,
								textureSizeMeters: 1,
								uv: false,
							},
							displayName: "Chrome",
							downloaded: 100,
							files: [
								{
									created: "2020-10-02T00:30:08.703676+02:00",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/24669/",
									fileThumbnail: "",
									fileThumbnailLarge: "",
									fileType: "blend",
									file_name: "blend_15a0c0b3-72c8-4335-b503-d78a6eb54e42.blend",
									modified: "2020-12-11T22:02:30.939391+01:00",
									resolution: "",
									url: "https://public.blenderkit.com/public-assets/assets/38b3663481a84c96b186e4fda91befba/files/blend_15a0c0b3-72c8-4335-b503-d78a6eb54e42.blend",
								},
								{
									created: "2020-10-05T14:49:32.557311+02:00",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/24844/",
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.1024x1024_q85_crop-%2C.png",
									fileType: "thumbnail",
									modified: "2020-12-11T22:02:30.921578+01:00",
									resolution: "",
								},
							],
							filesSize: 18319,
							id: "38b36634-81a8-4c96-b186-e4fda91befba",
							isFree: true,
							isPrivate: false,
							lastBlendUpload: "2020-10-01T22:30:08.703676+00:00",
							lastGltfUpload: "",
							lastResolutionUpload: "",
							lastThumbnailUpload: "2020-10-05T12:49:32.557311+00:00",
							lastUserInteraction: "2020-10-05T16:43:39.517582+02:00",
							lastVideoUpload: "",
							lastZipFileUpload: "",
							license: "royalty_free",
							max_resolution: 0,
							name: "Chrome",
							pk: 8982,
							ratingsAverage: {
								bookmarks: 0.99,
								quality: 9.142857142857142,
								virtualPrice: null,
								workingHours: 2.3,
							},
							ratingsCount: { bookmarks: 100, quality: 7, virtualPrice: 0, workingHours: 6 },
							ratingsMedian: { bookmarks: 1, quality: 10, virtualPrice: null, workingHours: 2.3 },
							ratingsSum: {
								bookmarks: 99,
								quality: 64,
								score: 210.28571428571425,
								virtualPrice: null,
								workingHours: 15.8,
							},
							score: 210.28571428571425,
							showMarketingLabels: true,
							sourceAppName: "blender",
							sourceAppVersion: "2.91.0",
							tags: ["chrome", "metal"],
							texture_size_meters: 1,
							thumbnail:
								"thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.512x512_q85_crop-%2C.png.webp",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.1024x1024_q85_crop-%2C.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.1024x1024_q85.png",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.1024x1024_q85.png.webp?webp_generated=1608306598",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1608306598",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.512x512_q85_crop-%2C.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.512x512_q85.png",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.512x512_q85.png.webp?webp_generated=1608306598",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.512x512_q85_crop-%2C.png.webp?webp_generated=1608306598",
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.256x256_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.256x256_q85.png",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.256x256_q85.png.webp?webp_generated=1608306598",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.256x256_q85_crop-%2C.png.webp?webp_generated=1608306598",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.2048x2048_q85_crop-%2C.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.2048x2048_q85.png",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.2048x2048_q85.png.webp?webp_generated=1608306598",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/38b3663481a84c96b186e4fda91befba/files/thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1608306598",
							thumbnail_small:
								"thumbnail_75f97ce3-008a-4f94-83ba-f172c3e23225.png.256x256_q85_crop-%2C.png.webp",
							tooltip_data: { aname: "Chrome", author_text: "by Nobody ", quality: "9" },
							url: "https://www.blenderkit.com/api/v1/assets/38b36634-81a8-4c96-b186-e4fda91befba/",
							verificationStatus: "validated",
							versionNumber: 1,
							webpGeneratedTimestamp: 1608306598,
							resolution: "resolution_2K",
						},
						"9c7dc589-186c-4b40-9b21-1a2b2ae2480b": {
							thumbnail:
								"thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.512x512_q85_crop-%2C.png.webp",
							thumbnail_small:
								"thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.256x256_q85_crop-%2C.png.webp",
							downloaded: 0,
							texture_size_meters: 1,
							pk: 4973,
							url: "https://www.blenderkit.com/api/v1/assets/a26b9b21-9752-4828-815c-c5d96d2a1fe7/",
							id: "a26b9b21-9752-4828-815c-c5d96d2a1fe7",
							assetBaseId: "9c7dc589-186c-4b40-9b21-1a2b2ae2480b",
							versionNumber: 1,
							author: {
								id: "31993",
								firstName: "Cyberking",
								lastName: "42",
								gravatarHash: "e583565e372f80164976348859f10b45",
								avatar128: "/avatar-redirect/bdd2164e-9682-4e1e-9e63-d8e149096dd7/128/",
								avatar256: "/avatar-redirect/bdd2164e-9682-4e1e-9e63-d8e149096dd7/256/",
								avatar512: "/avatar-redirect/bdd2164e-9682-4e1e-9e63-d8e149096dd7/512/",
								aboutMe: "100% Free Models & Materials.",
								aboutMeUrl: "https://www.behance.net/Cyberking-42",
								fullName: "Cyberking 42",
								socialNetworks: [],
							},
							name: "Refractive stylized glass",
							displayName: "Refractive stylized glass",
							description: "Refractive stylized Glass Texture.",
							descriptionHtml: "<p>Refractive stylized Glass Texture.</p>",
							assetType: "material",
							category: "glass",
							adult: false,
							isFree: true,
							tags: [
								"Glass",
								"Refractive",
								"Stylized",
								"Distortion",
								"Light Distortion",
								"Visual effects",
								"Light",
								"Glass surface",
							],
							license: "cc_zero",
							sourceAppName: "blender",
							sourceAppVersion: "2.83.5",
							addonVersion: "1.0.30",
							created: "2020-02-09T12:44:21.476308+01:00",
							lastUserInteraction: "2020-02-29T12:57:05.704603+01:00",
							verificationStatus: "validated",
							isPrivate: false,
							files: [
								{
									fileType: "blend",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/15490/",
									uuid: null,
									fileThumbnail: null,
									fileThumbnailLarge: null,
									created: "2020-02-29T12:54:37.781487+01:00",
									modified: "2020-12-11T21:21:53.150137+01:00",
									mimeType: null,
									resolution: null,
									url: "https://public.blenderkit.com/public-assets/assets/a26b9b2197524828815cc5d96d2a1fe7/files/blend_847b4a9a-7410-4b52-a6f4-cff77bea8d1b.blend",
									file_name: "blend_847b4a9a-7410-4b52-a6f4-cff77bea8d1b.blend",
								},
								{
									fileType: "thumbnail",
									downloadUrl: "https://www.blenderkit.com/api/v1/downloads/15488/",
									uuid: null,
									fileThumbnail:
										"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.96x96_q85_crop-%2C.png",
									fileThumbnailLarge:
										"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.1024x1024_q85_crop-%2C.png",
									created: "2020-02-29T12:38:18.342546+01:00",
									modified: "2020-12-11T21:21:53.175439+01:00",
									mimeType: null,
									resolution: null,
								},
							],
							filesSize: 328,
							thumbnailSmallUrl:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.256x256_q85_crop-%2C.png",
							thumbnailMiddleUrl:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.512x512_q85_crop-%2C.png",
							thumbnailLargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.1024x1024_q85_crop-%2C.png",
							thumbnailXlargeUrl:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.2048x2048_q85_crop-%2C.png",
							thumbnailSmallUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.256x256_q85.png",
							thumbnailMiddleUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.512x512_q85.png",
							thumbnailLargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.1024x1024_q85.png",
							thumbnailXlargeUrlNonsquared:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.2048x2048_q85.png",
							thumbnailSmallUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.256x256_q85_crop-%2C.png.webp?webp_generated=1693567851",
							thumbnailMiddleUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.512x512_q85_crop-%2C.png.webp?webp_generated=1693567851",
							thumbnailLargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.1024x1024_q85_crop-%2C.png.webp?webp_generated=1693567851",
							thumbnailXlargeUrlWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.2048x2048_q85_crop-%2C.png.webp?webp_generated=1693567851",
							thumbnailSmallUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.256x256_q85.png.webp?webp_generated=1693567851",
							thumbnailMiddleUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.512x512_q85.png.webp?webp_generated=1693567851",
							thumbnailLargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.1024x1024_q85.png.webp?webp_generated=1693567851",
							thumbnailXlargeUrlNonsquaredWebp:
								"https://public.blenderkit.com/thumbnails/assets/a26b9b2197524828815cc5d96d2a1fe7/files/thumbnail_7cff87ae-1717-43b6-bea9-af92497e4e36.png.2048x2048_q85.png.webp?webp_generated=1693567851",
							showMarketingLabels: true,
							webpGeneratedTimestamp: 1693567851,
							score: 83.63636363636363,
							ratingsMedian: { bookmarks: 1, workingHours: 1, quality: 10, virtualPrice: null },
							ratingsAverage: {
								bookmarks: 1,
								workingHours: 1,
								quality: 8.363636363636363,
								virtualPrice: null,
							},
							ratingsCount: { bookmarks: 25, workingHours: 9, quality: 11, virtualPrice: 0 },
							ratingsSum: {
								bookmarks: 25,
								workingHours: 14.8,
								quality: 92,
								virtualPrice: null,
								score: 83.63636363636363,
							},
							lastBlendUpload: "2020-02-29T11:54:37.781487+00:00",
							lastGltfUpload: null,
							lastZipFileUpload: null,
							lastThumbnailUpload: "2020-02-29T11:38:18.342546+00:00",
							lastVideoUpload: null,
							lastResolutionUpload: null,
							dictParameters: {
								textureSizeMeters: 1,
								procedural: true,
								materialStyle: "realistic",
								condition: "new",
								purePbr: true,
								engine: "cycles",
								shaders: ["refraction", "add shader"],
								pbrType: "metallic",
								uv: false,
								nodeCount: 13,
								textureCount: 0,
								megapixels: 0,
							},
							canDownload: true,
							canDownloadError: true,
							available_resolutions: [],
							max_resolution: 0,
							tooltip_data: {
								aname: "Refractive stylized glass",
								author_text: "by Cyberking 42",
								quality: "8",
							},
							resolution: "resolution_2K",
						},
					},
					uuid: "8efb5f30-a9c3-4fee-9688-16b27e8fd1c6",
					"assets reported": { "9c7dc589-186c-4b40-9b21-1a2b2ae2480b": true },
				}}>
				<mesh
					ref={ref}
					castShadow
					receiveShadow
					geometry={nodes.Mesh_0.geometry}
					rotation={[0, 0, Math.PI]}
					scale={1.57379186 * 5}
					userData={{ name: "Mesh_0" }}
					onClick={(event) => click(!clicked)}
					onPointerOver={(event) => hover(true)}
					onPointerOut={(event) => hover(false)}>
					<meshPhysicalMaterial {...materialProps} />
				</mesh>
			</group>
		</group>
	);
}

useGLTF.preload("/models/logo-model.glb");
