/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/HAPTIC_100_Logo_006.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/HAPTIC_100_Logo_006.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials['Translucent Plastic HOM']} position={[0, 0, -1.766]} rotation={[0, 0, -Math.PI]} scale={5.065}>
        <group rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.313}>
          <mesh geometry={nodes.FINAL_CIRCUIT_Albedo_1.geometry} material={materials['FINAL CIRCUIT_Albedo']} />
          <mesh geometry={nodes.FINAL_CIRCUIT_Albedo_2.geometry} material={materials.Material} />
        </group>
        <group rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.313}>
          <mesh geometry={nodes.FINAL_CIRCUIT_Albedo001_1.geometry} material={materials['FINAL CIRCUIT_Albedo']} />
          <mesh geometry={nodes.FINAL_CIRCUIT_Albedo001_2.geometry} material={materials.Material} />
        </group>
      </mesh>
      <group position={[-0.372, -0.131, -1.766]} scale={[1, 1, 0.726]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Dirrty white plastic']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Black Plastic']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Black Wire']} position={[-0.372, -0.179, -1.766]} scale={[0.008, 0.461, 0.008]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Black Plastic']} position={[-0.315, -0.478, -1.766]} scale={[0.014, 0.152, 0.014]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Chrome} position={[-0.372, -0.267, -1.766]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Chrome} position={[-0.372, -0.592, -1.766]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Chrome} position={[-0.314, -0.408, -1.766]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Chrome} position={[-0.399, -0.067, -1.772]} rotation={[0.092, -0.551, 0.978]} scale={[0.02, 0.04, 0.02]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Chrome} position={[-0.372, 0.089, -1.766]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Chrome} position={[-0.273, -0.038, -1.785]} rotation={[Math.PI / 2, 0, 0]} scale={[0.023, 0.017, 0.023]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Black Wire']} position={[-0.275, -0.179, -1.766]} scale={[0.008, 0.461, 0.008]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.Chrome} position={[-0.212, -0.617, -1.766]} scale={[0.028, 0.021, 0.028]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.Chrome} position={[-0.153, -0.623, -1.766]} scale={[0.02, 0.012, 0.02]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Chrome} position={[-0.417, -0.37, -1.785]} rotation={[Math.PI / 2, 0, 0]} scale={[0.023, 0.017, 0.023]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Black Wire']} position={[-0.45, -0.179, -1.766]} scale={[0.008, 0.339, 0.008]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.Material} position={[-0.414, -0.073, -1.774]} scale={[0.008, 0.272, 0.008]} />
      <mesh geometry={nodes.NurbsPath.geometry} material={materials['Black Plastic']} position={[-0.372, -0.131, -1.766]} rotation={[0, 0, Math.PI / 2]} scale={0.248} />
      <mesh geometry={nodes.NurbsPath001.geometry} material={materials['Black Plastic.001']} position={[-0.411, -0.131, -1.766]} rotation={[0, 0, Math.PI / 2]} scale={0.248} />
      <mesh geometry={nodes.NurbsPath002.geometry} material={materials['Black Plastic.001']} position={[-0.33, -0.131, -1.766]} rotation={[0, 0, Math.PI / 2]} scale={0.248} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Black Plastic']} position={[-0.361, -0.173, -1.792]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.302} />
      <group position={[0.373, 0.135, -1.766]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.726]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Dirrty white plastic']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Black Plastic']} />
      </group>
      <mesh geometry={nodes.Cylinder014.geometry} material={materials['Black Wire']} position={[0.373, 0.182, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.008, 0.461, 0.008]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['Black Plastic']} position={[0.315, 0.482, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.014, 0.152, 0.014]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Chrome} position={[0.373, 0.271, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.Chrome} position={[0.373, 0.595, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials.Chrome} position={[0.315, 0.412, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials.Chrome} position={[0.26, 0.08, -1.786]} scale={[0.02, 0.04, 0.02]} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials.Chrome} position={[0.373, -0.085, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.028, 0.054, 0.028]} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials.Chrome} position={[0.342, 0.01, -1.785]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.023, 0.017, 0.023]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['Black Wire']} position={[0.275, 0.182, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.008, 0.461, 0.008]} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials.Chrome} position={[0.213, 0.62, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.028, 0.021, 0.028]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.Chrome} position={[0.153, 0.627, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.02, 0.012, 0.02]} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials.Chrome} position={[0.417, 0.373, -1.785]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.023, 0.017, 0.023]} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials['Black Wire']} position={[0.451, 0.182, -1.766]} rotation={[0, 0, Math.PI]} scale={[0.008, 0.339, 0.008]} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials.Material} position={[0.414, 0.077, -1.774]} rotation={[0, 0, Math.PI]} scale={[0.008, 0.272, 0.008]} />
      <mesh geometry={nodes.NurbsPath003.geometry} material={materials['Black Plastic']} position={[0.373, 0.135, -1.766]} rotation={[0, 0, -Math.PI / 2]} scale={0.248} />
      <mesh geometry={nodes.NurbsPath004.geometry} material={materials['Black Plastic.001']} position={[0.411, 0.135, -1.766]} rotation={[0, 0, -Math.PI / 2]} scale={0.248} />
      <mesh geometry={nodes.NurbsPath005.geometry} material={materials['Black Plastic.001']} position={[0.33, 0.135, -1.766]} rotation={[0, 0, -Math.PI / 2]} scale={0.248} />
    </group>
  )
}

useGLTF.preload('/models/HAPTIC_100_Logo_006.glb')
