/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';

export function Model(props) {
    const { nodes, materials } = useGLTF('/models/logo.glb')
    const ref = useRef();

    const { camera, pointer } = useThree()
    const vec = new THREE.Vector3()
    useFrame((state, delta) => {
        camera.position.lerp(vec.set(pointer.x * -8, pointer.y * 2, camera.position.z), 0.02)

        // ref.current.rotation.y += delta / 1.2;
        // camera.position.lerp(vec.set(2, 0, camera.position.z), 0.02)
    })

    const [onClick, handleOnClick] = useState(false);

    const materialProps = {
        thickness: 1.6,
        roughness: 0,
        clearcoat: 0,
        clearcoatRoughness: 1,
        transmission: 0.98,
        ior: 6,
        envMapIntensity: 1,
        color: "#ffffff",
        attenuationTint: "#c10000",
        attenuationDistance: 1.2,
    };


    return (
        <group {...props} dispose={null} onClick={(event) => handleOnClick(!onClick)}
        >
            <mesh
                ref={ref}
                castShadow
                receiveShadow
                geometry={nodes.Mesh_0001.geometry}
                material={materials.Plastic}
                position={[0, 0, -1.766]}
                rotation={[0, 0, -Math.PI]}
                scale={5.065}
            >
                <meshPhysicalMaterial {...materialProps} />
            </mesh>

        </group>
    )
}

useGLTF.preload('/models/logo.glb')
